@host = film-watcher.herokuapp.com
 @contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGVvLmRvZGFAb3V0bG9vay5jb20iLCJ1c2VySWQiOiI2MjQyN2FhYWM4YTgzMTA5ZTBmZTQ0YmYiLCJpYXQiOjE2NDkxMTYyNjUsImV4cCI6MTY0OTExOTg2NX0.orFFzNzt9RFf7-OOyF6BTUviou4sGiuVcdhMMPbt1R8
 
###
get http://{{host}}/
 
###
# Signup
post http://{{host}}/auth/signup
Content-Type: {{contentType}}
 
{
 "name": "Mateo",
 "email": "mateo.doda@outlook.com",
 "password": "mateododa"
}
 
###
# Login 
post http://{{host}}/auth/login
Content-Type: {{contentType}}
 
{
 "email": "mateo.doda@outlook.com",
 "password": "mateododa"
}
 
###
# Logout user
put http://{{host}}/auth/logout
Authorization: Bearer {{token}}
 
###
# Get Watchlist
get http://{{host}}/movies/watchlist
Authorization: Bearer {{token}}
 
###
# Add To Watchlist
post http://{{host}}/movies/watchlist/623cbe8b622e693a014e06d1
Authorization: Bearer {{token}}
 
###
# DELETE from Watchlist
delete http://{{host}}/movies/watchlist/623cbe8b622e693a014e06d1
Authorization: Bearer {{token}}
 
###
# GET Favorites
get http://{{host}}/movies/favorites
Authorization: Bearer {{token}}
 
###
# Add To Favorites
post http://{{host}}/movies/favorites/623cbe8b622e693a014e06d2
Authorization: Bearer {{token}}
 
###
# DELETE from Favorites
delete http://{{host}}/movies/favorites/623cbe8b622e693a014e06d2
Authorization: Bearer {{token}}
 
###
# CLEAR Favorites
delete http://{{host}}/movies/favorites
Authorization: Bearer {{token}}
 
###
# Get movie suggestions
get http://{{host}}/movies/suggestions
Authorization: Bearer {{token}}
 
###
# ADD MOVIE 
post http://{{host}}/movies/add-movie
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
 
{
 "title": "Captain America: The Winter Soldier",
 "yearPublished": "2014",
 "rating": "PG-13",
 "minutes": "136 min",
 "genre": "Action",
 "imageUrl": "newdvdreleasedates.com/images/posters/full/captain-america-the-winter-soldier-2014-11.jpg",
 "description": "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.",
 "starRating": "5"
}
 
###
# DELETE MOVIE
delete http://{{host}}/movies/delete-movie/624b6af9ae2fa68496907609
Authorization: Bearer {{token}}
 
###
# UPDATE MOVIE
put http://{{host}}/movies/update-movie/623cbe8b622e693a014e06d1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}
 
{
 "title": "F9: The Fast Saga",
 "yearPublished": "2021",
 "rating": "PG-13",
 "minutes": "143 min",
 "genre": "Action",
 "imageUrl": "https://m.media-amazon.com/images/M/MV5BMjI0NmFkYzEtNzU2YS00NTg5LWIwYmMtNmQ1MTU0OGJjOTMxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_.jpg",
 "description": "Dom and the crew must take on an international terrorist who turns out to be Dom and Mia's estranged brother.",
 "starRating": "4"
}
 
###
# Approve movie
post http://{{host}}/movies/approve-movie/623cbe8b622e693a014e06d2
Authorization: Bearer {{token}}
 
###
# Deny movie
delete http://{{host}}/movies/deny-movie/623cbe8b622e693a014e06d3
Authorization: Bearer {{token}}
